language: python
python:
  - "2.7"
  - "3.5"
services:
  - mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -u root -e "CREATE DATABASE uxie;"
  - mysql -u root -e "CREATE USER 'uxie'@'localhost' IDENTIFIED BY 'uxie';"
  - mysql -u root -e "GRANT ALL ON uxie.* TO 'uxie'@'localhost';"
script: python -m unittest discover tests
